# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - potalmerchant

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest # 'windows-latest' also supported
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present
        env:
          API_URL: ${{ secrets.API_URL }}
          ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
          NEXT_PUBLIC_GHL_CLIENT_ID: ${{ secrets.NEXT_PUBLIC_GHL_CLIENT_ID }}
          NEXT_PUBLIC_GHL_REDIRECT_URI: ${{ secrets.NEXT_PUBLIC_GHL_REDIRECT_URI }}
          NEXT_PUBLIC_GHL_BASE_URL: ${{ secrets.NEXT_PUBLIC_GHL_BASE_URL }}
          CALENDLY_CLIENT_ID: ${{ secrets.CALENDLY_CLIENT_ID }}
          CALENDLY_REDIRECT_URI: ${{ secrets.CALENDLY_REDIRECT_URI }}
          NEXT_PUBLIC_OAUTH_REDIRECT_URI: ${{ secrets.NEXT_PUBLIC_OAUTH_REDIRECT_URI }}

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C9DF846DE3CF4775B34457CAF26AD0AB }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_4ED0FA6744C240BF838766C4806BAD16 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F78DAD3B2D604BFF90C559FA4343938A }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'potalmerchant'
          slot-name: 'Production'
          package: .
